In [219]:
import pandas as pd


df = pd.read_json(r"C:\Users\Vaibhav\OneDrive\Documents\masai\project\electricity_production_oil_sources\API_EG.ELC.PETR.ZS_DS2_en_csv_v2_4356435.json")
#df1 = pd.read_json(r"C:\Users\Vaibhav\OneDrive\Documents\masai\project\electricity_production_renewable_sources\API_EG.ELC.RNWX.KH_DS2_en_csv_v2_4356007.json")

In [221]:
df.drop(df.index[0],inplace=True)

In [222]:
df

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [223]:
headers = df.iloc[0]
df  = pd.DataFrame(df.values[1:], columns=headers)

In [224]:
temp3 = df

In [225]:
temp3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
0,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
2,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
4,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
262,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
263,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
264,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
265,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [173]:
df.dtypes

1
Country Name      object
Country Code      object
Indicator Name    object
Indicator Code    object
1960              object
                   ...
2018.0            object
2019.0            object
2020.0            object
2021.0            object
                  object
Length: 67, dtype: object

In [85]:
temp3 = df
#temp = df.iloc[:,4:]
temp3.head(3)

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
0,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
1,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
2,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,

In [228]:
lst =list(temp3.columns)
lst1 = []
lst.pop()

''

2021.0

In [230]:
for i in range(len(lst)):
    if(i<4):
        lst1.append(lst[i])
    else:
        lst1.append(int(lst[i]))

In [231]:
dic = {}
for i in range(len(lst)):
    if(i>4):
        dic[lst[i]]=lst1[i]

In [232]:
temp3.rename(columns = dic,inplace=True)

In [95]:
for i in temp3.columns:
    if(temp3[i].isnull().sum()==266):
        temp3.drop(i,axis=1,inplace=True)

In [116]:
temp3[2012].value_counts().shape

(159,)

In [236]:
temp3.to_csv('electricity_production_oil_sources.csv')

In [234]:
for i in temp3.columns:
    for j in temp3[i]:
        temp3[i]=pd.to_numeric(temp3[i],errors="ignore")

In [ ]:
temp3['Age'].fillna(temp3['Age'].mean(),inplace=True)#inplace :null val =true
data3['Age'].mean()
print(data3.isnull().sum())

In [118]:
for i in range(temp3.shape[0]):
    df[i][i]=df[][i].replace(",","")

1
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1990              float64
1991              float64
1992              float64
1993              float64
1994              float64
1995              float64
1996              float64
1997              float64
1998              float64
1999              float64
2000              float64
2001              float64
2002              float64
2003              float64
2004              float64
2005              float64
2006              float64
2007              float64
2008              float64
2009              float64
2010              float64
2011              float64
2012              float64
2013              float64
2014              float64
2015              float64
2016              float64
2017              float64
2018              float64
2019              float64
2020              float64
                  float64
dtype: object

In [235]:
temp3.dtypes

1
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960              float64
                   ...
2018              float64
2019              float64
2020              float64
2021              float64
                  float64
Length: 67, dtype: object

In [123]:
temp3.shape

(266, 36)

In [196]:
temp3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,
0,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.393182,10.594766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.200660,17.903147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,11.270691,11.265823,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,13.471264,15.047829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,25.761675,25.765106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.486840,8.393761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.563910,14.959867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,17.784744,16.437263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [124]:
df2 = pd.read_json(r"C:\Users\Vaibhav\OneDrive\Documents\masai\project\electricity_production_renewable_sources\API_EG.ELC.RNWX.KH_DS2_en_csv_v2_4356007.json")

In [128]:
df2.head(20)

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2.013000e+03,2.014000e+03,2.015000e+03,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.669000e+09,7.687000e+09,1.092600e+10,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,2.220000e+08,2.330000e+08,2.800000e+08,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
7,Albania,ALB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
8,Andorra,AND,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
9,Arab World,ARB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.534000e+09,4.457000e+09,5.117000e+09,NaN,NaN,NaN,NaN,NaN,NaN,
10,United Arab Emirates,ARE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000e+08,3.010000e+08,2.960000e+08,NaN,NaN,NaN,NaN,NaN,NaN,
11,Argentina,ARG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,2.942000e+09,2.719000e+09,2.752000e+09,NaN,NaN,NaN,NaN,NaN,NaN,
12,Armenia,ARM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,4.000000e+06,4.000000e+06,4.000000e+06,NaN,NaN,NaN,NaN,NaN,NaN,
13,American Samoa,ASM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
14,Antigua and Barbuda,ATG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
15,Australia,AUS,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,303000000.0,303000000.0,295000000.0,301000000.0,289000000.0,296000000.0,...,1.493900e+10,1.862200e+10,2.104400e+10,NaN,NaN,NaN,NaN,NaN,NaN,
16,Austria,AUT,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,8.322000e+09,8.934000e+09,1.018700e+10,NaN,NaN,NaN,NaN,NaN,NaN,
17,Azerbaijan,AZE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,6.900000e+07,9.200000e+07,1.010000e+08,NaN,NaN,NaN,NaN,NaN,NaN,
18,Burundi,BDI,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
19,Belgium,BEL,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,1.129500e+10,1.192100e+10,1.414800e+10,NaN,NaN,NaN,NaN,NaN,NaN,

In [153]:
dff = pd.read_json(r"C:\Users\Vaibhav\OneDrive\Documents\masai\project\access_to_elec_rural__world\API_EG.ELC.ACCS.RU.ZS_DS2_en_csv_v2_4364070.json")

In [158]:
dff

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
0,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
1,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
2,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
3,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,NaN,
4,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,,,3.81506657600403,,,7.33344507217407,,,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
262,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
263,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
264,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
265,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [157]:
headers = dff.iloc[0]
dff  = pd.DataFrame(dff.values[1:], columns=headers)

In [244]:
temp3.to_csv('electricity_production_nuclear_sources.csv')

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
261   NaN
262   NaN
263   NaN
264   NaN
265   NaN
Name: , Length: 266, dtype: float64

In [262]:
df1.to_csv('electricity_production_renewable_sources.csv')